
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.starwarsexpansion.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.starwarsexpansion.item.YellowLightsaberClosedItem;
import net.mcreator.starwarsexpansion.item.XWingItemItem;
import net.mcreator.starwarsexpansion.item.Westar34Item;
import net.mcreator.starwarsexpansion.item.VibrobladeItem;
import net.mcreator.starwarsexpansion.item.VibroAxeItem;
import net.mcreator.starwarsexpansion.item.TauntaunLeatherItem;
import net.mcreator.starwarsexpansion.item.TatooinePlanetAnchorItem;
import net.mcreator.starwarsexpansion.item.TIEFighterItemItem;
import net.mcreator.starwarsexpansion.item.TC14Item;
import net.mcreator.starwarsexpansion.item.T3M4ItemItem;
import net.mcreator.starwarsexpansion.item.StunBatonItem;
import net.mcreator.starwarsexpansion.item.StormtrooperArmorItem;
import net.mcreator.starwarsexpansion.item.StabilizerMaskItem;
import net.mcreator.starwarsexpansion.item.SpeederBikeItemItem;
import net.mcreator.starwarsexpansion.item.SnowspeederItemItem;
import net.mcreator.starwarsexpansion.item.SnowSuitItem;
import net.mcreator.starwarsexpansion.item.SithClothesItem;
import net.mcreator.starwarsexpansion.item.SaberHandleItem;
import net.mcreator.starwarsexpansion.item.SaberEmitterItem;
import net.mcreator.starwarsexpansion.item.RubberItem;
import net.mcreator.starwarsexpansion.item.ReparationKitItem;
import net.mcreator.starwarsexpansion.item.RedLightsaberClosedItem;
import net.mcreator.starwarsexpansion.item.RawBanthaMeatItem;
import net.mcreator.starwarsexpansion.item.R4P17Item;
import net.mcreator.starwarsexpansion.item.R2KTItem;
import net.mcreator.starwarsexpansion.item.R2D2Item;
import net.mcreator.starwarsexpansion.item.QuadaniumIngotItem;
import net.mcreator.starwarsexpansion.item.PurpleLightsaberClosedItem;
import net.mcreator.starwarsexpansion.item.PlastoidItem;
import net.mcreator.starwarsexpansion.item.MeiloorunItem;
import net.mcreator.starwarsexpansion.item.MSE6Item;
import net.mcreator.starwarsexpansion.item.LightsaberGeoYellowItem;
import net.mcreator.starwarsexpansion.item.LightsaberGeoPurpleItem;
import net.mcreator.starwarsexpansion.item.LightsaberGeoItem;
import net.mcreator.starwarsexpansion.item.LightsaberGeoGreenItem;
import net.mcreator.starwarsexpansion.item.LighstanerGeoRedItem;
import net.mcreator.starwarsexpansion.item.LandspeederItemItem;
import net.mcreator.starwarsexpansion.item.KyberCrystalYellowItem;
import net.mcreator.starwarsexpansion.item.KyberCrystalRedItem;
import net.mcreator.starwarsexpansion.item.KyberCrystalPurpleItem;
import net.mcreator.starwarsexpansion.item.KyberCrystalGreenItem;
import net.mcreator.starwarsexpansion.item.KyberCrystalBlueItem;
import net.mcreator.starwarsexpansion.item.KryknaStringItem;
import net.mcreator.starwarsexpansion.item.KryknaLegItem;
import net.mcreator.starwarsexpansion.item.JoganItem;
import net.mcreator.starwarsexpansion.item.JediTempleGuardArmorItem;
import net.mcreator.starwarsexpansion.item.InterfaceBandItem;
import net.mcreator.starwarsexpansion.item.I82Item;
import net.mcreator.starwarsexpansion.item.GreenLightsaberClosedItem;
import net.mcreator.starwarsexpansion.item.GrayJediClothesItem;
import net.mcreator.starwarsexpansion.item.GrandMasterJediClothesItem;
import net.mcreator.starwarsexpansion.item.GalacticCreditItem;
import net.mcreator.starwarsexpansion.item.GalacticCreditGoldItem;
import net.mcreator.starwarsexpansion.item.GaderffiiStickItem;
import net.mcreator.starwarsexpansion.item.GNKItem;
import net.mcreator.starwarsexpansion.item.EscapePodItemItem;
import net.mcreator.starwarsexpansion.item.ElectronicBoardItem;
import net.mcreator.starwarsexpansion.item.EE3Item;
import net.mcreator.starwarsexpansion.item.DooniumIngotItem;
import net.mcreator.starwarsexpansion.item.DooniumArmorItem;
import net.mcreator.starwarsexpansion.item.DL44Item;
import net.mcreator.starwarsexpansion.item.CookedBanthaMeatItem;
import net.mcreator.starwarsexpansion.item.ComputerTipItem;
import net.mcreator.starwarsexpansion.item.CloneArmorItem;
import net.mcreator.starwarsexpansion.item.CloneArmor501Item;
import net.mcreator.starwarsexpansion.item.CloneArmor41Item;
import net.mcreator.starwarsexpansion.item.CloneArmor212Item;
import net.mcreator.starwarsexpansion.item.C3POItem;
import net.mcreator.starwarsexpansion.item.BrownJediClothesItem;
import net.mcreator.starwarsexpansion.item.BlueLightsaberClosedItem;
import net.mcreator.starwarsexpansion.item.BlasterE11Item;
import net.mcreator.starwarsexpansion.item.BlackJediClothesItem;
import net.mcreator.starwarsexpansion.item.BeskarIngotItem;
import net.mcreator.starwarsexpansion.item.BeskarArmorItem;
import net.mcreator.starwarsexpansion.item.BanthaMilkItem;
import net.mcreator.starwarsexpansion.item.BanthaLeatherItem;
import net.mcreator.starwarsexpansion.item.BanhtaHornItem;
import net.mcreator.starwarsexpansion.item.B1Item;
import net.mcreator.starwarsexpansion.item.AurodiumIngotItem;
import net.mcreator.starwarsexpansion.item.ArgesFrogLegItem;
import net.mcreator.starwarsexpansion.item.ATSTItemItem;
import net.mcreator.starwarsexpansion.block.display.WorkspaceBenchDisplayItem;
import net.mcreator.starwarsexpansion.block.display.StatueDisplayItem;
import net.mcreator.starwarsexpansion.block.display.MoistureVaporatorDisplayItem;
import net.mcreator.starwarsexpansion.block.display.HolocronDisplayItem;
import net.mcreator.starwarsexpansion.block.display.ControlPanelDisplayItem;
import net.mcreator.starwarsexpansion.StarWarsExpansionMod;

public class StarWarsExpansionModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StarWarsExpansionMod.MODID);
	public static final RegistryObject<Item> BROWN_JEDI_CLOTHES_CHESTPLATE = REGISTRY.register("brown_jedi_clothes_chestplate", () -> new BrownJediClothesItem.Chestplate());
	public static final RegistryObject<Item> GRAY_JEDI_CLOTHES_CHESTPLATE = REGISTRY.register("gray_jedi_clothes_chestplate", () -> new GrayJediClothesItem.Chestplate());
	public static final RegistryObject<Item> BLACK_JEDI_CLOTHES_CHESTPLATE = REGISTRY.register("black_jedi_clothes_chestplate", () -> new BlackJediClothesItem.Chestplate());
	public static final RegistryObject<Item> CLONE_ARMOR_HELMET = REGISTRY.register("clone_armor_helmet", () -> new CloneArmorItem.Helmet());
	public static final RegistryObject<Item> CLONE_ARMOR_CHESTPLATE = REGISTRY.register("clone_armor_chestplate", () -> new CloneArmorItem.Chestplate());
	public static final RegistryObject<Item> CLONE_ARMOR_LEGGINGS = REGISTRY.register("clone_armor_leggings", () -> new CloneArmorItem.Leggings());
	public static final RegistryObject<Item> CLONE_ARMOR_501_HELMET = REGISTRY.register("clone_armor_501_helmet", () -> new CloneArmor501Item.Helmet());
	public static final RegistryObject<Item> CLONE_ARMOR_501_CHESTPLATE = REGISTRY.register("clone_armor_501_chestplate", () -> new CloneArmor501Item.Chestplate());
	public static final RegistryObject<Item> CLONE_ARMOR_501_LEGGINGS = REGISTRY.register("clone_armor_501_leggings", () -> new CloneArmor501Item.Leggings());
	public static final RegistryObject<Item> CLONE_ARMOR_212_HELMET = REGISTRY.register("clone_armor_212_helmet", () -> new CloneArmor212Item.Helmet());
	public static final RegistryObject<Item> CLONE_ARMOR_212_CHESTPLATE = REGISTRY.register("clone_armor_212_chestplate", () -> new CloneArmor212Item.Chestplate());
	public static final RegistryObject<Item> CLONE_ARMOR_212_LEGGINGS = REGISTRY.register("clone_armor_212_leggings", () -> new CloneArmor212Item.Leggings());
	public static final RegistryObject<Item> CLONE_ARMOR_41_HELMET = REGISTRY.register("clone_armor_41_helmet", () -> new CloneArmor41Item.Helmet());
	public static final RegistryObject<Item> CLONE_ARMOR_41_CHESTPLATE = REGISTRY.register("clone_armor_41_chestplate", () -> new CloneArmor41Item.Chestplate());
	public static final RegistryObject<Item> CLONE_ARMOR_41_LEGGINGS = REGISTRY.register("clone_armor_41_leggings", () -> new CloneArmor41Item.Leggings());
	public static final RegistryObject<Item> SITH_CLOTHES_CHESTPLATE = REGISTRY.register("sith_clothes_chestplate", () -> new SithClothesItem.Chestplate());
	public static final RegistryObject<Item> BLUE_LIGHTSABER_CLOSED = REGISTRY.register("blue_lightsaber_closed", () -> new BlueLightsaberClosedItem());
	public static final RegistryObject<Item> RED_LIGHTSABER_CLOSED = REGISTRY.register("red_lightsaber_closed", () -> new RedLightsaberClosedItem());
	public static final RegistryObject<Item> GREEN_LIGHTSABER_CLOSED = REGISTRY.register("green_lightsaber_closed", () -> new GreenLightsaberClosedItem());
	public static final RegistryObject<Item> YELLOW_LIGHTSABER_CLOSED = REGISTRY.register("yellow_lightsaber_closed", () -> new YellowLightsaberClosedItem());
	public static final RegistryObject<Item> PURPLE_LIGHTSABER_CLOSED = REGISTRY.register("purple_lightsaber_closed", () -> new PurpleLightsaberClosedItem());
	public static final RegistryObject<Item> KYBER_CRYSTAL_BLUE = REGISTRY.register("kyber_crystal_blue", () -> new KyberCrystalBlueItem());
	public static final RegistryObject<Item> KYBER_CRYSTAL_RED = REGISTRY.register("kyber_crystal_red", () -> new KyberCrystalRedItem());
	public static final RegistryObject<Item> KYBER_CRYSTAL_GREEN = REGISTRY.register("kyber_crystal_green", () -> new KyberCrystalGreenItem());
	public static final RegistryObject<Item> KYBER_CRYSTAL_YELLOW = REGISTRY.register("kyber_crystal_yellow", () -> new KyberCrystalYellowItem());
	public static final RegistryObject<Item> KYBER_CRYSTAL_PURPLE = REGISTRY.register("kyber_crystal_purple", () -> new KyberCrystalPurpleItem());
	public static final RegistryObject<Item> DOONIUM_INGOT = REGISTRY.register("doonium_ingot", () -> new DooniumIngotItem());
	public static final RegistryObject<Item> SABER_HANDLE = REGISTRY.register("saber_handle", () -> new SaberHandleItem());
	public static final RegistryObject<Item> GRAND_MASTER_JEDI_CLOTHES_CHESTPLATE = REGISTRY.register("grand_master_jedi_clothes_chestplate", () -> new GrandMasterJediClothesItem.Chestplate());
	public static final RegistryObject<Item> ASTROMECH_DROID_BLUE_SPAWN_EGG = REGISTRY.register("astromech_droid_blue_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.ASTROMECH_DROID_BLUE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PROTOCOL_DROID_GOLD_SPAWN_EGG = REGISTRY.register("protocol_droid_gold_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.PROTOCOL_DROID_GOLD, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> R_2_D_2 = REGISTRY.register("r_2_d_2", () -> new R2D2Item());
	public static final RegistryObject<Item> C_3_PO = REGISTRY.register("c_3_po", () -> new C3POItem());
	public static final RegistryObject<Item> ASTROMECH_DROID_RED_SPAWN_EGG = REGISTRY.register("astromech_droid_red_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.ASTROMECH_DROID_RED, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ASTROMECH_DROID_PINK_SPAWN_EGG = REGISTRY.register("astromech_droid_pink_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.ASTROMECH_DROID_PINK, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PROTOCOL_DROID_WHITE_SPAWN_EGG = REGISTRY.register("protocol_droid_white_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.PROTOCOL_DROID_WHITE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PROTOCOL_DROID_PINK_SPAWN_EGG = REGISTRY.register("protocol_droid_pink_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.PROTOCOL_DROID_PINK, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> R_4_P_17 = REGISTRY.register("r_4_p_17", () -> new R4P17Item());
	public static final RegistryObject<Item> R_2_KT = REGISTRY.register("r_2_kt", () -> new R2KTItem());
	public static final RegistryObject<Item> TC_14 = REGISTRY.register("tc_14", () -> new TC14Item());
	public static final RegistryObject<Item> I_82 = REGISTRY.register("i_82", () -> new I82Item());
	public static final RegistryObject<Item> GONK_DROID_SPAWN_EGG = REGISTRY.register("gonk_droid_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.GONK_DROID, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BLASTER_E_11 = REGISTRY.register("blaster_e_11", () -> new BlasterE11Item());
	public static final RegistryObject<Item> MOUSE_DROID_SPAWN_EGG = REGISTRY.register("mouse_droid_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.MOUSE_DROID, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BESKAR_ARMOR_HELMET = REGISTRY.register("beskar_armor_helmet", () -> new BeskarArmorItem.Helmet());
	public static final RegistryObject<Item> BESKAR_ARMOR_CHESTPLATE = REGISTRY.register("beskar_armor_chestplate", () -> new BeskarArmorItem.Chestplate());
	public static final RegistryObject<Item> BESKAR_ARMOR_LEGGINGS = REGISTRY.register("beskar_armor_leggings", () -> new BeskarArmorItem.Leggings());
	public static final RegistryObject<Item> BESKAR_INGOT = REGISTRY.register("beskar_ingot", () -> new BeskarIngotItem());
	public static final RegistryObject<Item> GNK = REGISTRY.register("gnk", () -> new GNKItem());
	public static final RegistryObject<Item> MSE_6 = REGISTRY.register("mse_6", () -> new MSE6Item());
	public static final RegistryObject<Item> RODIAN_GREEN_SPAWN_EGG = REGISTRY.register("rodian_green_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.RODIAN_GREEN, -13401522, -3164558, new Item.Properties()));
	public static final RegistryObject<Item> ITHORIAN_SPAWN_EGG = REGISTRY.register("ithorian_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.ITHORIAN, -8031670, -6147534, new Item.Properties()));
	public static final RegistryObject<Item> JAWA_SPAWN_EGG = REGISTRY.register("jawa_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.JAWA, -9813725, -15330284, new Item.Properties()));
	public static final RegistryObject<Item> TWI_LEK_DEFAULT_SPAWN_EGG = REGISTRY.register("twi_lek_default_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.TWI_LEK_DEFAULT, -13382401, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> TATOOINE_SAND = block(StarWarsExpansionModBlocks.TATOOINE_SAND);
	public static final RegistryObject<Item> TATOOINE_SANDSTONE = block(StarWarsExpansionModBlocks.TATOOINE_SANDSTONE);
	public static final RegistryObject<Item> TATOOINE_PLANET_ANCHOR = REGISTRY.register("tatooine_planet_anchor", () -> new TatooinePlanetAnchorItem());
	public static final RegistryObject<Item> TATOOINE_SANDSTONE_STAIRS = block(StarWarsExpansionModBlocks.TATOOINE_SANDSTONE_STAIRS);
	public static final RegistryObject<Item> TATOOINE_SANDSTONE_SLAB = block(StarWarsExpansionModBlocks.TATOOINE_SANDSTONE_SLAB);
	public static final RegistryObject<Item> TATOOINE_SANDSTONE_WALL = block(StarWarsExpansionModBlocks.TATOOINE_SANDSTONE_WALL);
	public static final RegistryObject<Item> TATOOINE_DOOR = doubleBlock(StarWarsExpansionModBlocks.TATOOINE_DOOR);
	public static final RegistryObject<Item> MODERN_LANTERN = block(StarWarsExpansionModBlocks.MODERN_LANTERN);
	public static final RegistryObject<Item> TUSKEN_RAIDER_SPAWN_EGG = REGISTRY.register("tusken_raider_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.TUSKEN_RAIDER, -5136017, -12042190, new Item.Properties()));
	public static final RegistryObject<Item> MOISTURE_VAPORATOR = REGISTRY.register(StarWarsExpansionModBlocks.MOISTURE_VAPORATOR.getId().getPath(),
			() -> new MoistureVaporatorDisplayItem(StarWarsExpansionModBlocks.MOISTURE_VAPORATOR.get(), new Item.Properties()));
	public static final RegistryObject<Item> VIBROBLADE = REGISTRY.register("vibroblade", () -> new VibrobladeItem());
	public static final RegistryObject<Item> BANTHA_SPAWN_EGG = REGISTRY.register("bantha_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.BANTHA, -11849185, -3099774, new Item.Properties()));
	public static final RegistryObject<Item> B_1 = REGISTRY.register("b_1", () -> new B1Item());
	public static final RegistryObject<Item> DOONIUM_ORE = block(StarWarsExpansionModBlocks.DOONIUM_ORE);
	public static final RegistryObject<Item> KRYKNA_SPAWN_EGG = REGISTRY.register("krykna_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.KRYKNA, -6710887, -10795422, new Item.Properties()));
	public static final RegistryObject<Item> RAW_BANTHA_MEAT = REGISTRY.register("raw_bantha_meat", () -> new RawBanthaMeatItem());
	public static final RegistryObject<Item> COOKED_BANTHA_MEAT = REGISTRY.register("cooked_bantha_meat", () -> new CookedBanthaMeatItem());
	public static final RegistryObject<Item> BANHTA_HORN = REGISTRY.register("banhta_horn", () -> new BanhtaHornItem());
	public static final RegistryObject<Item> METAL_BLOCK = block(StarWarsExpansionModBlocks.METAL_BLOCK);
	public static final RegistryObject<Item> METAL_STAIRS = block(StarWarsExpansionModBlocks.METAL_STAIRS);
	public static final RegistryObject<Item> METAL_SLAB = block(StarWarsExpansionModBlocks.METAL_SLAB);
	public static final RegistryObject<Item> WORKSPACE_BENCH = REGISTRY.register(StarWarsExpansionModBlocks.WORKSPACE_BENCH.getId().getPath(),
			() -> new WorkspaceBenchDisplayItem(StarWarsExpansionModBlocks.WORKSPACE_BENCH.get(), new Item.Properties()));
	public static final RegistryObject<Item> CONTROL_PANEL = REGISTRY.register(StarWarsExpansionModBlocks.CONTROL_PANEL.getId().getPath(), () -> new ControlPanelDisplayItem(StarWarsExpansionModBlocks.CONTROL_PANEL.get(), new Item.Properties()));
	public static final RegistryObject<Item> MODERN_PILLAR = block(StarWarsExpansionModBlocks.MODERN_PILLAR);
	public static final RegistryObject<Item> MODERN_STAIRS = block(StarWarsExpansionModBlocks.MODERN_STAIRS);
	public static final RegistryObject<Item> MODERN_SLAB = block(StarWarsExpansionModBlocks.MODERN_SLAB);
	public static final RegistryObject<Item> GALACTIC_CREDIT = REGISTRY.register("galactic_credit", () -> new GalacticCreditItem());
	public static final RegistryObject<Item> GALACTIC_CREDIT_GOLD = REGISTRY.register("galactic_credit_gold", () -> new GalacticCreditGoldItem());
	public static final RegistryObject<Item> KRYKNA_LEG = REGISTRY.register("krykna_leg", () -> new KryknaLegItem());
	public static final RegistryObject<Item> KRYKNA_STRING = REGISTRY.register("krykna_string", () -> new KryknaStringItem());
	public static final RegistryObject<Item> CANTINA_LIGHT = block(StarWarsExpansionModBlocks.CANTINA_LIGHT);
	public static final RegistryObject<Item> BANTHA_MILK = REGISTRY.register("bantha_milk", () -> new BanthaMilkItem());
	public static final RegistryObject<Item> MODERN_CRATE = block(StarWarsExpansionModBlocks.MODERN_CRATE);
	public static final RegistryObject<Item> MODERN_CRATE_2 = block(StarWarsExpansionModBlocks.MODERN_CRATE_2);
	public static final RegistryObject<Item> MODERN_CRATE_3 = block(StarWarsExpansionModBlocks.MODERN_CRATE_3);
	public static final RegistryObject<Item> MODERN_CRATE_4 = block(StarWarsExpansionModBlocks.MODERN_CRATE_4);
	public static final RegistryObject<Item> ARGES_FROG_SPAWN_EGG = REGISTRY.register("arges_frog_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.ARGES_FROG, -13369396, -16290194, new Item.Properties()));
	public static final RegistryObject<Item> ARGES_FROG_LEG = REGISTRY.register("arges_frog_leg", () -> new ArgesFrogLegItem());
	public static final RegistryObject<Item> MEILOORUN = REGISTRY.register("meiloorun", () -> new MeiloorunItem());
	public static final RegistryObject<Item> JOGAN = REGISTRY.register("jogan", () -> new JoganItem());
	public static final RegistryObject<Item> HUMAN_SPAWN_EGG = REGISTRY.register("human_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.HUMAN, -13210, -10332883, new Item.Properties()));
	public static final RegistryObject<Item> LANDSPEEDER_ITEM = REGISTRY.register("landspeeder_item", () -> new LandspeederItemItem());
	public static final RegistryObject<Item> DOONIUM_ARMOR_CHESTPLATE = REGISTRY.register("doonium_armor_chestplate", () -> new DooniumArmorItem.Chestplate());
	public static final RegistryObject<Item> DOONIUM_ARMOR_LEGGINGS = REGISTRY.register("doonium_armor_leggings", () -> new DooniumArmorItem.Leggings());
	public static final RegistryObject<Item> PLASTOID = REGISTRY.register("plastoid", () -> new PlastoidItem());
	public static final RegistryObject<Item> RUBBER_ORE = block(StarWarsExpansionModBlocks.RUBBER_ORE);
	public static final RegistryObject<Item> RUBBER = REGISTRY.register("rubber", () -> new RubberItem());
	public static final RegistryObject<Item> X_WING_ITEM = REGISTRY.register("x_wing_item", () -> new XWingItemItem());
	public static final RegistryObject<Item> COMPUTER_TIP = REGISTRY.register("computer_tip", () -> new ComputerTipItem());
	public static final RegistryObject<Item> BANTHA_LEATHER = REGISTRY.register("bantha_leather", () -> new BanthaLeatherItem());
	public static final RegistryObject<Item> STABILIZER_MASK_HELMET = REGISTRY.register("stabilizer_mask_helmet", () -> new StabilizerMaskItem.Helmet());
	public static final RegistryObject<Item> QUADANIUM_ORE = block(StarWarsExpansionModBlocks.QUADANIUM_ORE);
	public static final RegistryObject<Item> QUADANIUM_INGOT = REGISTRY.register("quadanium_ingot", () -> new QuadaniumIngotItem());
	public static final RegistryObject<Item> ELECTRONIC_BOARD = REGISTRY.register("electronic_board", () -> new ElectronicBoardItem());
	public static final RegistryObject<Item> SABER_EMITTER = REGISTRY.register("saber_emitter", () -> new SaberEmitterItem());
	public static final RegistryObject<Item> JEDI_TEMPLE_GUARD_ARMOR_HELMET = REGISTRY.register("jedi_temple_guard_armor_helmet", () -> new JediTempleGuardArmorItem.Helmet());
	public static final RegistryObject<Item> JEDI_TEMPLE_GUARD_ARMOR_CHESTPLATE = REGISTRY.register("jedi_temple_guard_armor_chestplate", () -> new JediTempleGuardArmorItem.Chestplate());
	public static final RegistryObject<Item> JEDI_TEMPLE_GUARD_ARMOR_LEGGINGS = REGISTRY.register("jedi_temple_guard_armor_leggings", () -> new JediTempleGuardArmorItem.Leggings());
	public static final RegistryObject<Item> MODERN_BOOKSHELF = block(StarWarsExpansionModBlocks.MODERN_BOOKSHELF);
	public static final RegistryObject<Item> HOLOCRON = REGISTRY.register(StarWarsExpansionModBlocks.HOLOCRON.getId().getPath(), () -> new HolocronDisplayItem(StarWarsExpansionModBlocks.HOLOCRON.get(), new Item.Properties()));
	public static final RegistryObject<Item> STATUE = REGISTRY.register(StarWarsExpansionModBlocks.STATUE.getId().getPath(), () -> new StatueDisplayItem(StarWarsExpansionModBlocks.STATUE.get(), new Item.Properties()));
	public static final RegistryObject<Item> T_3_M_4_SPAWN_EGG = REGISTRY.register("t_3_m_4_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.T_3_M_4, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> T_3_M_4_ITEM = REGISTRY.register("t_3_m_4_item", () -> new T3M4ItemItem());
	public static final RegistryObject<Item> LIGHTSABER_GEO = REGISTRY.register("lightsaber_geo", () -> new LightsaberGeoItem());
	public static final RegistryObject<Item> LIGHSTANER_GEO_RED = REGISTRY.register("lighstaner_geo_red", () -> new LighstanerGeoRedItem());
	public static final RegistryObject<Item> LIGHTSABER_GEO_GREEN = REGISTRY.register("lightsaber_geo_green", () -> new LightsaberGeoGreenItem());
	public static final RegistryObject<Item> LIGHTSABER_GEO_YELLOW = REGISTRY.register("lightsaber_geo_yellow", () -> new LightsaberGeoYellowItem());
	public static final RegistryObject<Item> LIGHTSABER_GEO_PURPLE = REGISTRY.register("lightsaber_geo_purple", () -> new LightsaberGeoPurpleItem());
	public static final RegistryObject<Item> SPEEDER_BIKE_ITEM = REGISTRY.register("speeder_bike_item", () -> new SpeederBikeItemItem());
	public static final RegistryObject<Item> TIE_FIGHTER_ITEM = REGISTRY.register("tie_fighter_item", () -> new TIEFighterItemItem());
	public static final RegistryObject<Item> ESCAPE_POD_ITEM = REGISTRY.register("escape_pod_item", () -> new EscapePodItemItem());
	public static final RegistryObject<Item> REPARATION_KIT = REGISTRY.register("reparation_kit", () -> new ReparationKitItem());
	public static final RegistryObject<Item> VIBRO_AXE = REGISTRY.register("vibro_axe", () -> new VibroAxeItem());
	public static final RegistryObject<Item> INTERFACE_BAND_HELMET = REGISTRY.register("interface_band_helmet", () -> new InterfaceBandItem.Helmet());
	public static final RegistryObject<Item> STUN_BATON = REGISTRY.register("stun_baton", () -> new StunBatonItem());
	public static final RegistryObject<Item> COPPER_SANDSTONE_ORE = block(StarWarsExpansionModBlocks.COPPER_SANDSTONE_ORE);
	public static final RegistryObject<Item> DL_44 = REGISTRY.register("dl_44", () -> new DL44Item());
	public static final RegistryObject<Item> WESTAR_34 = REGISTRY.register("westar_34", () -> new Westar34Item());
	public static final RegistryObject<Item> EE_3 = REGISTRY.register("ee_3", () -> new EE3Item());
	public static final RegistryObject<Item> GADERFFII_STICK = REGISTRY.register("gaderffii_stick", () -> new GaderffiiStickItem());
	public static final RegistryObject<Item> ATST_ITEM = REGISTRY.register("atst_item", () -> new ATSTItemItem());
	public static final RegistryObject<Item> STORMTROOPER_ARMOR_HELMET = REGISTRY.register("stormtrooper_armor_helmet", () -> new StormtrooperArmorItem.Helmet());
	public static final RegistryObject<Item> STORMTROOPER_ARMOR_CHESTPLATE = REGISTRY.register("stormtrooper_armor_chestplate", () -> new StormtrooperArmorItem.Chestplate());
	public static final RegistryObject<Item> STORMTROOPER_ARMOR_LEGGINGS = REGISTRY.register("stormtrooper_armor_leggings", () -> new StormtrooperArmorItem.Leggings());
	public static final RegistryObject<Item> HOTH_SNOW = block(StarWarsExpansionModBlocks.HOTH_SNOW);
	public static final RegistryObject<Item> SNOWSPEEDER_ITEM = REGISTRY.register("snowspeeder_item", () -> new SnowspeederItemItem());
	public static final RegistryObject<Item> TAUNTAUN_SPAWN_EGG = REGISTRY.register("tauntaun_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.TAUNTAUN, -6710887, -7974318, new Item.Properties()));
	public static final RegistryObject<Item> TAUNTAUN_LEATHER = REGISTRY.register("tauntaun_leather", () -> new TauntaunLeatherItem());
	public static final RegistryObject<Item> SNOW_SUIT_HELMET = REGISTRY.register("snow_suit_helmet", () -> new SnowSuitItem.Helmet());
	public static final RegistryObject<Item> SNOW_SUIT_CHESTPLATE = REGISTRY.register("snow_suit_chestplate", () -> new SnowSuitItem.Chestplate());
	public static final RegistryObject<Item> SNOW_SUIT_LEGGINGS = REGISTRY.register("snow_suit_leggings", () -> new SnowSuitItem.Leggings());
	public static final RegistryObject<Item> HOTH_STONE = block(StarWarsExpansionModBlocks.HOTH_STONE);
	public static final RegistryObject<Item> AURODIUM_ORE = block(StarWarsExpansionModBlocks.AURODIUM_ORE);
	public static final RegistryObject<Item> AURODIUM_INGOT = REGISTRY.register("aurodium_ingot", () -> new AurodiumIngotItem());
	public static final RegistryObject<Item> GAMORREAN_SPAWN_EGG = REGISTRY.register("gamorrean_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.GAMORREAN, -12293321, -10732258, new Item.Properties()));
	public static final RegistryObject<Item> HUTT_SPAWN_EGG = REGISTRY.register("hutt_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.HUTT, -13219786, -3823007, new Item.Properties()));
	public static final RegistryObject<Item> METAL_TRAPDOOR = block(StarWarsExpansionModBlocks.METAL_TRAPDOOR);
	public static final RegistryObject<Item> GRID_METAL_BLOCK = block(StarWarsExpansionModBlocks.GRID_METAL_BLOCK);
	public static final RegistryObject<Item> PIRATE_SPAWN_EGG = REGISTRY.register("pirate_spawn_egg", () -> new ForgeSpawnEggItem(StarWarsExpansionModEntities.PIRATE, -4671429, -10840260, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
